apiVersion: v1
kind: Pod
metadata:
  name: nginx-node-selector
  namespace:
  labels:
    run: nginx
spec:
  nodeSelector:
    namespace: production
    customer: pippo
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 80
