kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: default-sa
  namespace:
subjects:
- kind: ServiceAccount
  name: default 
roleRef:
  kind: Role
  name: default-sa
  namespace:
  apiGroup: rbac.authorization.k8s.io
