# Secrets to pass CHAP credential to iSCSI initiator pods
# On each worker node, set CHAP credentials in /etc/iscsi/iscsid.conf
# echo -n "kubernetes" | base64
# a3ViZXJuZXRlcw==
# echo -n "password" | base64
# cGFzc3dvcmQ=
# In the user namespace create the secret as:
# kubectl create -f iscsi-chap-secret.yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: iscsi-chap-secret
  namespace: project
type: "kubernetes.io/iscsi-chap"
data:
  node.session.auth.username: a3ViZXJuZXRlcw==
  node.session.auth.password: cGFzc3dvcmQ=
