kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-with-selector
spec:
  storageClassName: nfs-dynamic
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: "persistent-volume"