apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod-two
  namespace:
  labels:
spec:
  containers:
  - name: container-1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: data
  volumes:
    - name: data
      persistentVolumeClaim:
        claimName: volume-claim
