apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
  annotations:
spec:
  rules:
  - host: service00.apps.noverit.osc.link
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx
          servicePort: 80
