apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
spec:
  containers:
  - name: nginx
    image: nginx:latest
    ports:
    - containerPort: 8080
    volumeMounts:
      - name: config
        mountPath: /etc/nginx/conf.d/custom.conf
        subPath: custom.conf
        readOnly: true
  volumes:
    - name: config
      configMap:
        name: nginx
