apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  namespace:
  labels:
spec:
  replicas: 3
  selector:
    run: nginx
  template:
    metadata:
      name: nginx
      labels:
        run: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
