apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace:
  labels:
    run: nginx
spec:
  containers:
  - name: container-1
    image: nginx:latest
    ports:
    - containerPort: 80
    volumeMounts:
    - name: tz-config
      mountPath: /etc/localtime
      readOnly: true
  volumes:
    - name: tz-config
      hostPath:
        path: /usr/share/zoneinfo/Europe/Rome
        type: File
