apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
  namespace:
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
  selector:
    run: nginx
    # multiple label selectors are permitted
    # app: web
  type: ClusterIP
  sessionAffinity: None
