apiVersion: v1
kind: Service
metadata:
  name: nginx-lb
  labels:
    run: nginx
spec:
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 8080
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8443
  selector:
    run: nginx
  type: LoadBalancer
