apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  labels:
  namespace:
spec:
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 80
  selector:
    run: nginx
  type: ClusterIP
  clusterIP: None
