apiVersion: v1
kind: Pod
metadata:
  name: nginx-port
  namespace:
  labels:
    run: nginx
spec:
  containers:
  - name: container
    image: nginx:latest
    ports:
    - name: http
      protocol: TCP
      containerPort: 80 # nginx can be reached on port 80 of the container
      hostPort: 8090 # nginx can be also reached on port 8090 of the host (kubelet)
