apiVersion: v1
kind: Service
metadata:
  name: nginx-np
  labels:
  namespace:
spec:
  ports:
  - name: regular
    protocol: TCP
    #nodePort: 30080 
    port: 80
    targetPort: 80
  - name: metrics
    protocol: TCP
    #nodePort: 30080 
    port: 8080
    targetPort: 8080
  selector:
    run: nginx
  type: NodePort
