apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-config
  namespace: kube-system
data:
  traefik.toml: |+
    ################################################################
    # Global configuration
    ################################################################

    debug = false
    logLevel = "INFO"

    defaultEntryPoints = ["https"] #["http"]

    [entryPoints]
      [entryPoints.http]
      address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"

      [entryPoints.https]
      address = ":443"
        [entryPoints.https.tls]
        [entryPoints.https.tls.defaultCertificate]
          certFile = "/opt/certs/tls.crt"
          keyFile = "/opt/certs/tls.key"

      [entryPoints.api]
      address = ":8080"

      [entryPoints.metrics]
      address = ":9090"
    
    ################################################################
    # Enable Let's Encrypt automatic SSL
    ################################################################
    #[acme]
    #email = "info@noverit.com"
    #storage = "acme.json"
    #entryPoint = "https" 
    #onHostRule = true
    #[acme.httpChallenge]
    #entryPoint = "http"
    ################################################################
    # Traefik logs configuration
    ################################################################
    [traefikLog]
    format = "json"
    ################################################################
    # Access logs configuration
    ################################################################
    [accessLog]
    format = "json"
    ################################################################
    # API and dashboard configuration
    ################################################################
    [api]
      entryPoint = "api"
      dashboard = true
    ################################################################
    # Prometheus Metrics
    ################################################################
    [metrics]
      [metrics.prometheus]
        entryPoint = "metrics"
        # Buckets for latency metrics
        buckets = [0.1,0.3,1.2,5.0,9.0,12.0]
