apiVersion: v1
data:
  reading.sh: |
    #!/bin/bash
    while true;
    do
        echo "Sending next query"
        sleep 2; 
        mysql -h mysql-ro -D employees -u root -e 'SELECT @@server_id,NOW(); SELECT COUNT(*) FROM employees'
        echo ""
    done
kind: ConfigMap
metadata:
  name: setup