apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
  namespace:
spec:
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  - name: metrics
    protocol: TCP
    port: 8080
    targetPort: 8080
  selector:
    run: mysql
  type: NodePort
