# Client service for connecting to any MySQL instance for reads.
# # For writes, you must instead connect to the master: mysql-0.mysql.
apiVersion: v1
kind: Service
metadata:
  name: mysql-ro
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
