apiVersion: apps/v1
kind: ReplicaSet
metadata:
  labels:
  namespace:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        ports:
        - containerPort: 3306
          protocol: TCP
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
