apiVersion: v1
kind: Pod
metadata:
  name: mysql-client
  namespace:
  labels:
spec:
  containers:
  - name: mysql
    image: mysql
    command: ["/bin/bash", "/mnt/reading.sh"]  
    volumeMounts:
    - name: script
      mountPath: /mnt
  volumes:
  - name: script
    configMap:
      name: setup
      defaultMode: 0700