apiVersion: v1
kind: Pod
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
  name: keepalived
  namespace: kube-system
  labels:
    component: keepalived
    tier: control-plane
spec:
  tolerations:
  - key: node-role.kubernetes.io/master
    effect: NoSchedule
  priorityClassName: system-cluster-critical
  hostNetwork: true
  containers:
  - image: kalise/keepalived:1.0
    name: keepalived
    volumeMounts:
    - name: config
      mountPath: /etc/keepalived
      readOnly: true
    resources:
      requests:
        cpu: 100m
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
  volumes:
  - name: config
    hostPath:
      path: /etc/keepalived