apiVersion: velero.io/v1
kind: Restore
metadata:
  name: production
  namespace: velero
spec:
  backupName: production
  excludedNamespaces: null
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.velero.io
  - restores.velero.io
  - resticrepositories.velero.io
  includedNamespaces:
  - '*'
  includedResources: null
  namespaceMapping: {}
