apiVersion: v1
data:
  cloud: W2RlZmF1bHRdCmF3c19hY2Nlc3Nfa2V5X2lkID0gbWluaW8KYXdzX3NlY3JldF9hY2Nlc3Nfa2V5ID0gbWluaW8xMjMK
kind: Secret
metadata:
  creationTimestamp: null
  labels:
    component: velero
  name: cloud-credentials
  namespace: velero
type: Opaque