
# image from https://github.com/mhausenblas/mehdb
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: optd
spec:
  selector:
    matchLabels:
      app: optd
  serviceName: optd
  replicas: 3
  template:
    metadata:
      labels:
        app: optd
    spec:
      containers:
      - name: optd
        image: kalise/optd:latest
        ports:
        - containerPort: 9876
        env:
        - name: MEHDB_DATADIR
          value: "/mehdbdata"
        livenessProbe:
          initialDelaySeconds: 2
          periodSeconds: 10
          httpGet:
            path: /status
            port: 9876
        readinessProbe:
          initialDelaySeconds: 15
          periodSeconds: 30
          httpGet:
            path: /status?level=full
            port: 9876
        volumeMounts:
        - name: data
          mountPath: /mehdbdata
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      #storageClassName: standard
      resources:
        requests:
          storage: 1Gi