apiVersion: v1
kind: ReplicationController
metadata:
  name: website
  namespace:
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: centos/httpd:latest
        ports:
        - containerPort: 80
