---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    run: ingress-default-backend
  name: ingress-default-backend
  namespace: kube-system
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: ingress-default-backend
    spec:
      containers:
      - image: gcr.io/google_containers/defaultbackend:1.0
        name: ingress-default-backend
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            cpu: 10m
            memory: 20Mi
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: ingress-default-backend
  namespace: kube-system
  labels:
    run: ingress-default-backend
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    run: ingress-default-backend
  type: ClusterIP
