---
# The role binding to combine the ingress controller service account and the cluser-admin role
# Required since the ingress-controller service account cannot access APIs in the kube-system namespace
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: ingress-controller
subjects:
- kind: ServiceAccount
  name: ingress-controller
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-controller
  namespace: kube-system