apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: kube.noverit.com
  namespace: 
spec:
  secretName: noverit-tls
  issuerRef:
    kind: ClusterIssuer
    #name: letsencrypt-staging
    name: letsencrypt-prod
  commonName: kube.noverit.com
  dnsNames:
  - kube.noverit.com
  acme:
    config:
    - http01:
        # A new ingress resource will be created in order to solve the challenge.
        # This new resource will have an annotation with key kubernetes.io/ingress.class "traefik"
        ingressClass: traefik
      domains:
      - kube.noverit.com
