apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  # credits: https://github.com/oliver006/redis_exporter
  namespace:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:4
        ports:
        - containerPort: 6379
      - name: redis-exporter
        image: oliver006/redis_exporter:latest
        ports:
        - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-metrics
  namespace:
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9121"
spec:
  ports:
  - port: 9121
    name: redis-metrics
  selector:
    app: redis