# by default, the kube-mgmt sidecar will load policies from configmaps
# labelled as openpolicyagent.org/policy=rego
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: opa-default-system-main
  namespace: webhooks
  labels:
    openpolicyagent.org/policy: rego
data:
  main: |
    package system
    import data.kubernetes.admission
    main = {
      "apiVersion": "admission.k8s.io/v1beta1",
      "kind": "AdmissionReview",
      "response": response,
    }
    default response = {"allowed": true}
    response = {
        "allowed": false,
        "status": {
            "reason": reason,
        },
    } {
        reason = concat(", ", admission.deny)
        reason != ""
    }