apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: test-opa
spec:
  rules:
  - host: cmp.local
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 80